"""System endpoints: health, time simulation, settings, logs, sync, CRL."""

from __future__ import annotations

import csv
import io

from fastapi import APIRouter, HTTPException, Query, Response, status
from fastapi.responses import PlainTextResponse

from .. import __version__, schemas
from ..config import get_settings as load_settings
from ..deps import DB, Admin, Auth, Operator
from ..services import cert_service, secret_store

router = APIRouter(tags=["system"])


@router.get("/health", response_model=schemas.Health)
async def health() -> schemas.Health:
    return schemas.Health(status="ok", app=load_settings().app_name, version=__version__)


@router.get("/time", response_model=schemas.TimeInfo)
async def get_time(db: DB, _auth: Auth) -> schemas.TimeInfo:
    return await cert_service.time_info(db)


@router.post("/time/advance", response_model=schemas.TimeInfo)
async def advance_time(
    payload: schemas.TimeAdvance, db: DB, _op: Operator = None
) -> schemas.TimeInfo:
    offset = await cert_service.advance_time(db, payload.days)

    # Mirror the original dashboard: advancing time triggers eligible auto-renewals.
    eligible = await cert_service.auto_renew_eligible(db)
    for cert in eligible:
        await cert_service.log_entry(
            db,
            f"[AUTO-RENEW TRIGGER] {cert.cn} is within renewal window - triggering ACME...",
            "acme",
            cert.id,
        )
        await cert_service.renew_cert(db, cert, reason="auto")

    await db.commit()
    return schemas.TimeInfo(
        sim_now=(await cert_service.sim_now(db)).date().isoformat(),
        real_now=cert_service.utcnow().date().isoformat(),
        offset_days=offset,
    )


@router.post("/time/reset", response_model=schemas.TimeInfo)
async def reset_time(db: DB, _op: Operator = None) -> schemas.TimeInfo:
    await cert_service.reset_time(db)
    await cert_service.log_entry(db, "Simulated date reset to today", "info")
    await db.commit()
    return await cert_service.time_info(db)


@router.get("/settings", response_model=schemas.SettingsRead)
async def get_settings(db: DB, _auth: Auth) -> schemas.SettingsRead:
    return await cert_service.read_settings(db)


@router.put("/settings", response_model=schemas.SettingsRead)
async def put_settings(
    payload: schemas.SettingsUpdate, db: DB, _admin: Admin = None
) -> schemas.SettingsRead:
    try:
        await cert_service.update_settings(db, payload)
    except ValueError as exc:
        raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, detail=str(exc)) from exc
    await cert_service.log_entry(
        db, "Saved ACME provider & reverse-proxy webhook configuration", "success"
    )
    await db.commit()
    return await cert_service.read_settings(db)


@router.get("/system/health")
async def system_health(db: DB, _auth: Auth) -> dict:
    """Extended health: scheduler config + optional Vault reachability."""
    info = {
        "secrets_backend": "vault" if secret_store.vault_configured() else "local",
        "scheduler_enabled": load_settings().scheduler_enabled,
        "scheduler_interval_seconds": load_settings().scheduler_interval_seconds,
        "provider": await cert_service.get_provider_name(db),
    }
    if secret_store.vault_configured():
        info["vault"] = secret_store.vault_health()
    return info


@router.get("/crl")
async def download_crl(db: DB, _auth: Auth) -> Response:
    """Download the CRL generated by the locally-configured CA (if any)."""
    settings = load_settings()
    if not (settings.ca_cert_path and settings.ca_key_path):
        # Managed in-DB CA (favored): create one via POST /api/ca/root.
        material = await cert_service.get_ocsp_signing_material(db)
        if material is None:
            raise HTTPException(
                status.HTTP_501_NOT_IMPLEMENTED,
                "No CA configured - create a local CA (POST /api/ca/root) or set "
                "TROVE_CA_CERT_PATH / TROVE_CA_KEY_PATH",
            )
    pem = await cert_service.build_crl_pem(db)
    return PlainTextResponse(
        content=pem or "",
        media_type="application/pkix-crl",
        headers={"Content-Disposition": 'attachment; filename="trove.crl"'},
    )


@router.post("/sync", response_model=schemas.SyncResult)
async def sync(db: DB, _op: Operator = None) -> schemas.SyncResult:
    ok, message = await cert_service.sync(db)
    await db.commit()
    return schemas.SyncResult(ok=ok, message=message)


@router.get("/logs", response_model=list[schemas.LogRead])
async def get_logs(
    db: DB,
    _auth: Auth,
    limit: int = Query(200, ge=1, le=1000),
) -> list[schemas.LogRead]:
    rows = await cert_service.list_logs(db, limit)
    return [
        schemas.LogRead(
            id=r.id, cert_id=r.cert_id, level=r.level, message=r.message, created_at=r.created_at
        )
        for r in rows
    ]


@router.get("/logs/export")
async def export_logs(db: DB, _auth: Auth) -> Response:
    rows = await cert_service.list_logs(db, 1000)
    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=["id", "cert_id", "level", "message", "created_at"])
    writer.writeheader()
    for r in rows:
        writer.writerow(
            {
                "id": r.id,
                "cert_id": r.cert_id or "",
                "level": r.level,
                "message": r.message,
                "created_at": r.created_at,
            }
        )
    return Response(
        content=out.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="trove-logs.csv"'},
    )


@router.delete("/logs")
async def clear_logs(db: DB, _op: Operator = None) -> dict[str, bool]:
    await cert_service.clear_logs(db)
    await db.commit()
    return {"ok": True}
