"""Pydantic schemas."""

from app.dockwatch.schemas.docker import (
    ActivityEvent,
    ContainerDeploy,
    ContainerDeployResponse,
    ContainerDetail,
    ContainerRead,
    ContainerStats,
    DockerStatus,
    ImagePullRequest,
    ImagePullResponse,
    ImageRead,
    LogsResponse,
    ServiceRead,
    StackRead,
    SwarmNode,
)
from app.dockwatch.schemas.endpoint import (
    EndpointCreate,
    EndpointRead,
    EndpointStatus,
    EndpointUpdate,
    FleetOverview,
)
from app.dockwatch.schemas.inventory import (
    DeviceCreate,
    DeviceRead,
    DeviceUpdate,
    InventoryOverview,
    IPAddressCreate,
    IPAddressRead,
    IPAddressUpdate,
    RackCreate,
    RackRead,
    RackUpdate,
    SearchResult,
    SiteCreate,
    SiteRead,
    SiteUpdate,
)
from app.dockwatch.schemas.links import (
    ContainerHotlink,
    ContainerLinkRead,
    ContainerLinkUpdate,
    ContainerLinkView,
    DiscoveryResult,
    MapToGatewayRequest,
    MapToGatewayResult,
)
from app.dockwatch.schemas.security import ImageScanDetail, ImageScanRead, ScanRequest

__all__ = [
    "ActivityEvent",
    "ContainerDeploy",
    "ContainerDeployResponse",
    "ContainerDetail",
    "ContainerHotlink",
    "ContainerLinkRead",
    "ContainerLinkUpdate",
    "ContainerLinkView",
    "ContainerRead",
    "ContainerRankingEntry",
    "ContainerStats",
    "DeviceCreate",
    "DeviceRead",
    "DeviceUpdate",
    "DiscoveryResult",
    "DockerStatus",
    "EndpointCreate",
    "EndpointRead",
    "EndpointStatus",
    "EndpointUpdate",
    "FleetOverview",
    "IPAddressCreate",
    "IPAddressRead",
    "IPAddressUpdate",
    "ImagePullRequest",
    "ImagePullResponse",
    "ImageRead",
    "ImageScanDetail",
    "ImageScanRead",
    "InventoryOverview",
    "LogsResponse",
    "MapToGatewayRequest",
    "MapToGatewayResult",
    "RackCreate",
    "RackRead",
    "RackUpdate",
    "ScanRequest",
    "SearchResult",
    "ServiceRead",
    "SiteCreate",
    "SiteRead",
    "SiteUpdate",
    "StackRead",
    "SwarmNode",
]
